---
title: "Untitled"
output: html_document
date: "2024-11-26"
---

#PHYLOGENETIC TREE
```{r}
phylo<-readNexus("~/Desktop/Menstrual taboos/R CODE DATA FILES (USE)/Time-calibrated SCCS supertree ultrametric.nex") #Load the phylogeny
```

#MAKE CULTURE NAMES THE ROWNAMES IN DATAFRAME
```{r}
rownames(Combo.df) <- Combo.df$tip.label #Set rownames in data frame

pop <- Combo.df[,2] #Store the population column
```

#CLEAN PHYLOGENETIC TREE FOR ANALYSIS
```{r}
#name.check (phylo,Combo.df$tip.label) # check which populations are in the tree but not in the data and remove them; we remove those populations that have missing data for any of the outcomes
MT_Tree <- drop.tip (phylo, tip=c("Abipon", "Abkhaz", "Ajie", "Atayal", "Aweikoma", "Banen", "Basseri", "Bogo", "Cayua", "Fur_Darfur", "Gheg_Albanians", "Haitians", "Hausa", "Hebrews", "Ifugao", "Khalka_Mongols", "Konso", "Lamet", "Mao", "Mbau_Fijians", "MISSING_Botocudo", "MISSING_Kafa_Kaffa", "MISSING_Kutenai", "MISSING_Natchez", "MISSING_Timbira", "MISSING_Twana", "Mundurucu", "Negri_Sembilan", "New_Ireland", "Nicobarese", "Orokaiva", "Palauans", "Pentecost", "Popoluca", "Punjabi_West", "Rhade", "Russians", "Shilluk", "Suku", "Tobelorese", "Turks",  "Uttar_Pradesh"))

name.check (MT_Tree, Combo.df) # OK
write.tree (MT_Tree, "MT.Phylo") # write the reduced tree

phylo.Reduced <- read.tree("MT.Phylo")

phylo_vcv <- vcv.phylo(phylo, cor=TRUE)
phylo.reduced <- vcv.phylo(phylo.Reduced, cor=TRUE)
```

```{r}
saveRDS(phylo.reduced, file = "PrunedPhylo.rds")
```